version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3001'

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=application_database
      - MYSQL_USER=dimundra
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
